// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjlfdlejeimqxluebweb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbGZkbGVqZWltcXhsdWVid2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzkyMzAsImV4cCI6MjA1NDk1NTIzMH0.KlnYHdVh7UrfXjrMq3fsNjI1pnPuA7Gxu8_3HTYRW_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);